"use client";

import { useEffect, useState } from "react";
import Navigation from "@/components/navigation";

const blankMovie = { title: "", year: "2024", rating: "8.0", genre: "", categories: "", image: "" };

export default function AdminPage() {
  const [movies, setMovies] = useState([]); const [form, setForm] = useState(blankMovie); const [editingId, setEditingId] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function loadMovies() { const response = await fetch("/api/admin/movies"); const data = await response.json(); setMovies(data.movies); }
  useEffect(() => { loadMovies(); }, []);
  function change(event) { setForm({ ...form, [event.target.name]: event.target.value }); }
  function edit(movie) { setEditingId(movie.id); setForm({ title: movie.title, year: movie.year, rating: movie.rating || "", genre: movie.genre || movie.category || "", categories: movie.categories.join(", "), image: movie.image }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function submit(event) { event.preventDefault(); setSaving(true); setMessage(""); const response = await fetch("/api/admin/movies", { method: editingId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, id: editingId }) }); const data = await response.json(); setSaving(false); if (!response.ok) return setMessage(data.error || "Could not save movie."); setMessage(editingId ? "Movie updated." : "Movie created."); setForm(blankMovie); setEditingId(""); loadMovies(); }
  async function remove(id) { if (!window.confirm("Delete this movie from the catalog?")) return; const response = await fetch("/api/admin/movies", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); if (!response.ok) return setMessage("Could not delete movie."); setMessage("Movie deleted."); loadMovies(); }
  return <main className="app-shell"><Navigation/><section className="content page-content admin-page"><span className="eyebrow">CONTENT MANAGEMENT</span><h1 className="page-title">Admin <i>Dashboard.</i></h1><div className="admin-summary"><span><b>{movies.length}</b> catalog titles</span><span><b>{new Set(movies.flatMap((movie) => movie.categories || [])).size}</b> categories</span><span>Changes publish instantly</span></div><div className="admin-layout"><form className="movie-form" onSubmit={submit}><div className="form-heading"><h2>{editingId ? "Edit movie" : "Add new movie"}</h2>{editingId && <button type="button" onClick={() => { setEditingId(""); setForm(blankMovie); }}>Cancel</button>}</div><label>Movie title<input required name="title" value={form.title} onChange={change} placeholder="Movie title" /></label><div className="form-pair"><label>Year<input name="year" value={form.year} onChange={change} inputMode="numeric" /></label><label>Rating<input name="rating" value={form.rating} onChange={change} inputMode="decimal" /></label></div><label>Categories<input required name="categories" value={form.categories} onChange={change} placeholder="Action, Sci-Fi" /></label><label>Display genre<input name="genre" value={form.genre} onChange={change} placeholder="Action · Sci-Fi" /></label><label>Poster image URL<input name="image" value={form.image} onChange={change} placeholder="https://..." /></label><button className="watch-button" disabled={saving}>{saving ? "Saving..." : editingId ? "Update movie" : "Publish movie"}</button>{message && <p className="admin-message" role="status">{message}</p>}</form><div className="admin-catalog"><div className="form-heading"><h2>Catalog</h2><span>{movies.length} titles</span></div>{movies.map((movie) => <article className="admin-movie" key={movie.id}><img src={movie.image} alt=""/><div><h3>{movie.title}</h3><p>{movie.genre || movie.category}</p><small>{movie.year} · ★ {movie.rating || "N/A"}</small></div><div><button onClick={() => edit(movie)}>Edit</button><button className="delete-button" onClick={() => remove(movie.id)}>Delete</button></div></article>)}</div></div></section></main>;
}
