"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import Navigation from "@/components/navigation";

const filters = ["All", "Action", "Adventure", "Comedy", "Drama", "Mystery", "Romance", "Sci-Fi", "Thriller"];
const categoryCards = [{ name: "Action", image: "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=500&q=80" }, { name: "Sci-Fi", image: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=500&q=80" }, { name: "Romance", image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=500&q=80" }, { name: "Mystery", image: "https://images.unsplash.com/photo-1519608487953-e999c86e7453?auto=format&fit=crop&w=500&q=80" }];

export default function DiscoverPage() {
  const [query, setQuery] = useState(""); const [movies, setMovies] = useState([]); const [savedIds, setSavedIds] = useState(new Set()); const [filter, setFilter] = useState("All"); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch("/api/watchlist").then((response) => response.json()).then((list) => setSavedIds(new Set(list.movieIds))).catch(() => {}); }, []);
  useEffect(() => { const timer = setTimeout(async () => { setLoading(true); try { const params = new URLSearchParams(); if (query.trim()) params.set("q", query); if (filter !== "All") params.set("category", filter); const response = await fetch(`/api/movies?${params}`); const data = await response.json(); setMovies(data.movies); } catch { setMessage("Could not search the movie library."); } finally { setLoading(false); } }, 250); return () => clearTimeout(timer); }, [query, filter]);
  async function toggleList(movieId) { const saved = savedIds.has(movieId); const response = await fetch("/api/watchlist", { method: saved ? "DELETE" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ movieId }) }); if (!response.ok) return setMessage("Could not update My List."); const data = await response.json(); setSavedIds(new Set(data.movieIds)); setMessage(saved ? "Removed from My List." : "Added to My List."); }
  return <main className="app-shell"><Navigation/><section className="content page-content"><span className="eyebrow">EXPLORE THE LIBRARY</span><h1 className="page-title">Discover your next <i>favorite.</i></h1><label className="search discover-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search titles, genres, or categories" /></label><div className="category-strip">{categoryCards.map((category) => <button key={category.name} onClick={() => setFilter(category.name)} style={{ backgroundImage: `linear-gradient(90deg, rgba(0,0,0,.66), rgba(0,0,0,.05)), url(${category.image})` }}><span>{category.name}</span><small>Explore →</small></button>)}</div><div className="filter-row">{filters.map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item}</button>)}</div>{message && <p className="status-message discover-message" role="status">{message}</p>}{loading ? <p className="empty">Searching the library...</p> : <><div className="discover-grid">{movies.map((movie) => <article className="movie-card" key={movie.id}><div className="poster-wrap"><Link className="poster" href={`/watch/${movie.id}`}><img src={movie.image} alt={`${movie.title} poster`} /><span className="score">★ {movie.rating || "8.3"}</span></Link><button className={savedIds.has(movie.id) ? "card-save saved-poster" : "card-save"} onClick={() => toggleList(movie.id)} aria-label={`Toggle ${movie.title} in My List`}>⌑</button></div><h3>{movie.title}</h3><p>{movie.genre || movie.category}</p></article>)}</div>{!movies.length && <p className="empty">No matching movies found.</p>}</>}</section></main>;
}
